title: Yu Seung Kim
logo: /assets/img/yskim.png
description: Cyber-Physical System Security (Medical Devices, Automotive Platforms, Data Privacy, IoT, Cloud, Wireless, Mobile)
show_downloads: no
is_project_page: no
baseurl: "/"
google_analytics:
theme: jekyll-theme-minimal
